Improve CS.
Install "google-cloud-sdk".

Remove "usb-creator".

Use "google chrome" instead of "chromium".

diff --git a/src/system/usr/local/sbin/systemctl-user b/src/system/usr/local/sbin/systemctl-user
--- a/src/system/usr/local/sbin/systemctl-user
+++ b/src/system/usr/local/sbin/systemctl-user
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 if [ "$#" -lt 2 ] ; then
-    echo "Invalid number of arguments." 1>&2
-    echo "Usage: $(basename "$0") [USER] [...]" 1>&2
+    echo 1>&2 "Invalid number of arguments."
+    echo 1>&2 "Usage: $(basename "$0") [USER] [...]"
     exit 1
 fi
 
